/*
 * Copyright  2019 ACRIOS Systems
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* DEFINITION VALUES START */
#define CLOG_PRINT_DETAILS_ID_DEFAULT 0
#define CLOG_PRINT_DETAILS_ID_USER    1

#define CLOG_PRINT_FUNC_ID_STDLIB 0
#define CLOG_PRINT_FUNC_ID_NXP    1
/* DEFINITION VALUES END */

/* CONFIGURATION OPTIONS */
#define CLOG_PRINT_DETAILS_ID CLOG_PRINT_DETAILS_ID_DEFAULT

#define CLOG_PRINT_FUNC_ID CLOG_PRINT_FUNC_ID_STDLIB

#define CLOG_PRINT_DETAILS_USE_FILENAME

#define CLOG_PRINT_DETAILS_USE_LINENUMBER
