/*
 * Copyright  2019-2023 ACRIOS Systems
 * All rights reserved.
 *
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _CLOG_CONFIG_
#define _CLOG_CONFIG_

/* VALUES DEFINITION START */
#define CLOG_PRINT_DETAILS_ID_DEFAULT 0
#define CLOG_PRINT_DETAILS_ID_USER    1

#define CLOG_STR_NONE     "NONE"
#define CLOG_STR_CRITICAL "CRITICAL"
#define CLOG_STR_ERROR    "ERROR"
#define CLOG_STR_WARNING  "WARNING"
#define CLOG_STR_INFO     "INFO"
#define CLOG_STR_DEBUG    "DEBUG"
#define CLOG_STR_TRACE    "TRACE"

#define CLOG_COLOR_RED     "\x1b[31m"
#define CLOG_COLOR_GREEN   "\x1b[32m"
#define CLOG_COLOR_YELLOW  "\x1b[33m"
#define CLOG_COLOR_BLUE    "\x1b[34m"
#define CLOG_COLOR_WHITE   "\x1b[37m"
#define CLOG_COLOR_MAGENTA "\x1b[35m"
#define CLOG_COLOR_DEF     "\x1b[39m"
/* VALUES DEFINITION END */

/* CONFIGURATION OPTIONS */
#define CLOG_PRINT_DETAILS_ID CLOG_PRINT_DETAILS_ID_DEFAULT

#define CLOG_PRINT_DETAILS_USE_FILENAME

#define CLOG_PRINT_DETAILS_USE_LINENUMBER

#define CLOG_STRING_CRITICAL CLOG_STR_CRITICAL
#define CLOG_STRING_ERROR    CLOG_STR_ERROR
#define CLOG_STRING_WARNING  CLOG_STR_WARNING
#define CLOG_STRING_INFO     CLOG_STR_INFO
#define CLOG_STRING_DEBUG    CLOG_STR_DEBUG
#define CLOG_STRING_TRACE    CLOG_STR_TRACE

#define CLOG_COLOR_CRITICAL CLOG_COLOR_MAGENTA
#define CLOG_COLOR_ERROR    CLOG_COLOR_RED
#define CLOG_COLOR_WARNING  CLOG_COLOR_YELLOW
#define CLOG_COLOR_INFO     CLOG_COLOR_GREEN
#define CLOG_COLOR_DEBUG    CLOG_COLOR_BLUE
#define CLOG_COLOR_TRACE    CLOG_COLOR_WHITE
#define CLOG_COLOR_DEFAULT  CLOG_COLOR_DEF

#endif /* _CLOG_CONFIG_ */
